import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import { cookies } from 'next/headers';
import UIDGenerator from '@/auth/tracking';
import { checkCurrentUser } from '@/auth/login';
import { getSiteSettings } from "@/get-api-data/settings";
import VisitorsRecord from "@/auth/visitorsRecord";
import NavbarContainer from "@/models/navbar";
import TopBannerContainer from "@/models/topbanner"; // Corrected import
import { ReduxProvider } from "@/redux/provider";

const outfit = Outfit({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
  variable: "--font-outfit",
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const sid = cookieStore.get('sid')?.value;
  const uid = cookieStore.get('uid')?.value;
  const { isLoggedin, data: user } = await checkCurrentUser();
  const settings = await getSiteSettings();

  const sessionData = {
    isLoggedin,
    user,
    sid,
    uid,
  };

  const preloadedState = {
    settingsReducer: settings,
    session: sessionData,
  }


  return (
    <html lang="en">
      <body
        className={`${outfit.className} antialiased`}
      >
        <ReduxProvider preloadedState={preloadedState}> {/* Pass preloadedState */}
          <TopBannerContainer /> {/* Corrected usage */}
          <NavbarContainer />
          {!uid && <UIDGenerator />}
          {children}
          <VisitorsRecord />
        </ReduxProvider>
      </body>
    </html>
  );
}